### ISSUE TITLE
Artifacts on screen after hovering on catalog services

### ISSUE THREAD

**Issue by ncameronbritt** [openshift/origin-web-console#2038]
See the faint blue lines between service icons. 
![screen shot 2017-09-08 at 3 50 40 pm](https://user-images.githubusercontent.com/8974593/30229626-acc2f49a-94b0-11e7-80a3-cf9f55f7b4f2.png)

Seems to only happen on my external display using Chrome on macOS.

**Comment by ncameronbritt** [comment]
cc @rhamilto

**Comment by rhamilto** [comment]
Best I can tell, this is a result of gpu rasterization as disabling gpu rasterization at chrome://flags/#enable-gpu-rasterization prevents the bug.  Now for how we fix it without telling users to disable gpu rasterization...

**Comment by rhamilto** [comment]
>Best I can tell, this is a result of gpu rasterization as disabling gpu rasterization at chrome://flags/#enable-gpu-rasterization prevents the bug. Now for how we fix it without telling users to disable gpu rasterization...

@ncameronbritt, did you get a chance to test disabling gpu rasterization with your Thunderbolt Display?

**Comment by ncameronbritt** [comment]
Sorry for letting this slip. Looks like that does indeed take care of it.  

I didn't have the problem consistently even with the default gpu rasterization settings, or maybe it's the case that the effect is sometimes so subtle that I haven't noticed.

**Comment by rhamilto** [comment]
With Chrome Version 64.0.3282.167, I am unable to reproduce.  I suspect this means the bug was fixed in Chrome.  @ncameronbritt is to test to confirm the bug no longer exists tomorrow (Tue Feb 20).  If he's unable to reproduce, he will close this issue.

**Comment by ncameronbritt** [comment]
I'm still seeing the artifacts with Chrome version 64.0.3282.167

![screen shot 2018-02-20 at 9 01 29 am](https://user-images.githubusercontent.com/8974593/36428040-d042fd46-161c-11e8-919e-110009de49ae.png)

**Comment by ncameronbritt** [comment]
As before, disabling GPU Rasterization seems to fix it.
